-- =============================================
-- FARMARED 88 - Complete Database Schema
-- Run this in the Supabase SQL Editor
-- NOTE: Safe to re-run - drops existing policies first
-- =============================================

-- 1. Create Products table with discount support
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  image text,
  price decimal(10,2) not null,
  description text,
  discount_percent int default 0,
  is_daily_deal boolean default false,
  stock int default 100,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Profiles table
create table if not exists profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Orders table
create table if not exists orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  total_amount decimal(10,2) not null,
  items_json jsonb not null,
  shipping_address text,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS
alter table products enable row level security;
alter table profiles enable row level security;
alter table orders enable row level security;

-- 5. DROP existing policies (prevents "already exists" error)
drop policy if exists "Anyone can view products" on products;
drop policy if exists "Users can view own profile" on profiles;
drop policy if exists "Users can update own profile" on profiles;
drop policy if exists "Users can view own orders" on orders;
drop policy if exists "Users can create orders" on orders;

-- 6. Create policies
create policy "Anyone can view products" on products for select using (true);
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);
create policy "Users can view own orders" on orders for select using (auth.uid() = user_id);
create policy "Users can create orders" on orders for insert with check (auth.uid() = user_id);

-- 7. Trigger for auto profile creation
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- =============================================
-- SEED DATA: Products (only inserts if not exists)
-- =============================================

insert into products (id, name, category, image, price, description, discount_percent, is_daily_deal)
select * from (values
(1, 'Paracetamol 500mg', 'Medicamentos', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Tylenol_bottle_closeup.jpg/220px-Tylenol_bottle_closeup.jpg', 4.50, 'Alivido efectivo para el dolor y la fiebre.', 20, true),
(2, 'Ibuprofeno 400mg', 'Medicamentos', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/IbuprofenBottle.JPG/220px-IbuprofenBottle.JPG', 5.20, 'Antiinflamatorio no esteroideo.', 0, false),
(3, 'Aspirina Botella Grande', 'Medicamentos', 'https://upload.wikimedia.org/wikipedia/commons/6/67/Big_Aspirin_Bottle.jpg', 8.90, 'Analgésico clásico.', 15, true),
(4, 'Aspirina (Pastillas)', 'Medicamentos', 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Aspirin_%281%29.jpg', 3.50, 'Formato de viaje.', 0, false),
(5, 'Doxiciclina', 'Medicamentos', 'https://upload.wikimedia.org/wikipedia/commons/9/98/Bottle_of_Doxycycline_%2837280175550%29.jpg', 12.00, 'Antibiótico. Venta con receta.', 10, true),
(6, 'Jarabe para Tos', 'Medicamentos', 'https://upload.wikimedia.org/wikipedia/commons/4/42/Vintage_Turkish_pediatric_cough_syrup_bottle.png', 7.80, 'Alivio para la tos.', 0, false),
(7, 'Pastillas Garganta', 'Medicamentos', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVdbdbLoWNn5BtmiqlMMnXebsgA-LDZy-LIQ&s', 4.00, 'Suaviza la garganta.', 0, false),
(8, 'Ungüento Dérmico', 'Medicamentos', 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Diprosalic_ointment_tube.jpeg', 6.50, 'Afecciones de piel.', 0, false),
(9, 'Vitamina C (Botella)', 'Suplementos', 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Vitamin_C_supplements_1.jpg', 9.90, 'Sistema inmunológico.', 25, true),
(10, 'Vitamina C (Pastillas)', 'Suplementos', 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Vitamin_C_Tablets.jpg', 5.50, 'Efervescentes.', 0, false),
(11, 'Aceite de Pescado', 'Suplementos', 'https://upload.wikimedia.org/wikipedia/commons/1/16/Fish_Oil_Capsules.jpg', 14.50, 'Omega 3.', 30, true),
(12, 'Multivitamínico', 'Suplementos', 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Multivitamin_product.jpg', 18.00, 'Vitaminas completas.', 0, false),
(13, 'Estetoscopio', 'Equipo Médico', 'https://upload.wikimedia.org/wikipedia/commons/4/41/STETHOSCOPE.jpg', 45.00, 'Profesional.', 0, false),
(14, 'Medidor Presión', 'Equipo Médico', 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Sphygmomanometer.JPG', 32.00, 'Arterial preciso.', 15, true),
(15, 'Pack Jeringas', 'Equipo Médico', 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Syringe_with_needle_%282%29.JPG', 8.50, 'Estériles.', 0, false),
(16, 'Silla de Ruedas', 'Equipo Médico', 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Wheelchair.JPEG', 150.00, 'Plegable.', 0, false),
(17, 'Guantes Látex', 'Equipo Médico', 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Latex_gloves-pair.jpg', 6.00, 'Caja 50 pares.', 0, false),
(18, 'Botiquín Pared', 'Primeros Auxilios', 'https://upload.wikimedia.org/wikipedia/commons/3/3e/First_aid_kit_on_wall.jpg', 25.00, 'Completo.', 20, true),
(19, 'Vendas Elásticas', 'Primeros Auxilios', 'https://upload.wikimedia.org/wikipedia/commons/1/17/Bandage.jpg', 2.50, 'Soporte.', 0, false),
(20, 'Termómetro', 'Primeros Auxilios', 'https://http2.mlstatic.com/D_NQ_NP_965915-MLU70525033567_072023-O.webp', 5.90, 'Lectura rápida.', 0, false),
(21, 'Alcohol Antiséptico', 'Primeros Auxilios', 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Rubbing_alcohol.JPG', 3.00, 'Desinfección.', 0, false),
(22, 'Mascarillas', 'Primeros Auxilios', 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Surgical_face_mask.jpg', 4.50, 'Pack 10.', 0, false),
(23, 'Bolsa Agua Caliente', 'Primeros Auxilios', 'https://upload.wikimedia.org/wikipedia/commons/5/53/Hot_water_bottle.jpg', 10.00, 'Dolores musculares.', 0, false),
(24, 'Desinfectante Manos', 'Cuidado Personal', 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Hand_sanitizer.jpg', 3.50, '99.9% gérmenes.', 0, false),
(25, 'Pasta Dental', 'Cuidado Personal', 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Tube.jpg', 2.80, 'Anticaries.', 0, false),
(26, 'Shampoo', 'Cuidado Personal', 'https://upload.wikimedia.org/wikipedia/commons/5/59/Metric_shampoo_bottle.jpg', 6.20, 'Revitalizante.', 0, false),
(27, 'Jabón Barra', 'Cuidado Personal', 'https://upload.wikimedia.org/wikipedia/commons/5/5e/A_bar_of_soap.jpg', 1.50, 'Hidratante.', 0, false),
(28, 'Gotas Ojos', 'Cuidado Personal', 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Eye_drop.jpg', 5.80, 'Ojos secos.', 0, false),
(29, 'Hisopos', 'Cuidado Personal', 'https://i5.walmartimages.com/seo/Q-tips-Cotton-Swabs-Original-375-Count_f802e608-9a92-49cd-930d-068248af16a7.387c1952c8c79339811cfdb51e6d2884.jpeg', 2.00, 'Algodón natural.', 0, false),
(30, 'Gafas Lectura', 'Cuidado Personal', 'https://upload.wikimedia.org/wikipedia/commons/6/61/Reading-Glasses.jpg', 12.00, 'Cómodas.', 0, false),
(31, 'Pañales', 'Bebés', 'https://bebemundo.ec/cdn/shop/files/0037000765141-7.png?v=1709582027', 18.50, 'Alta absorción.', 10, true)
) as v(id, name, category, image, price, description, discount_percent, is_daily_deal)
where not exists (select 1 from products where products.id = v.id);
